pub mod avg_salary;
pub mod best_closing_time;
pub mod combination_sum;
pub mod connect_points;
pub mod count_order;
pub mod counting_bits;
pub mod deci_binary_partition;
pub mod extra_characters_in_string;
pub mod goal_interpreter;
pub mod height_balanced_bst;
pub mod insert_gcd_linked_list;
pub mod is_palindrome;
pub mod jewels_stones;
pub mod k_weakest_rows;
pub mod min_cost_of_walk;
pub mod min_effort_path;
pub mod num_ways;
pub mod pascal_triangle;
pub mod remove_duplicate_letters;
pub mod shuffle;
pub mod sort_arr_by_parity;
pub mod split_linked_list;
pub mod sum_even_grandparent;
pub mod two_sum;
pub mod unique_paths;

pub fn main() {
    best_closing_time::solve();
    counting_bits::solve();
    is_palindrome::solve();
    counting_bits::solve();
    connect_points::solve();
    min_effort_path::solve();
    two_sum::solve();
    extra_characters_in_string::solve();
    avg_salary::solve();
    height_balanced_bst::solve();
    unique_paths::solve();
    deci_binary_partition::solve();
    split_linked_list::solve();
    pascal_triangle::solve();
    combination_sum::solve();
    jewels_stones::solve();
    count_order::solve();
    goal_interpreter::solve();
    k_weakest_rows::solve();
    remove_duplicate_letters::solve();
    sort_arr_by_parity::solve();
    num_ways::solve();
}
